@uri=http://localhost:3001/web/api/heroes/

###

GET {{uri}}categories

###

POST {{uri}}categories
Content-Type: application/json

{
  "name":"news"
}

###
// http://localhost:3001/web/api/heroes/5dd0f9041992c73e88576eb9
GET {{uri}}5dd0f9041992c73e88576eb9 HTTP/1.1
